### ISSUE TITLE
[Website Internal] Upgrade Docsy theme, resolve related issues

### ISSUE THREAD

**Issue by chipzoller** [kyverno/website#564]
### Description

The Kyverno website uses Google's [Docsy theme](https://www.docsy.dev) along with Hugo and may not have ever been updated. We need to update the Docsy theme and its dependencies so we stay current with the capabilities of both it and Hugo. For example, we're now starting to see the following rendering warnings with Hugo that probably would be resolved in more current versions of Docsy.

```
WARN 2022/06/09 19:43:26 The google_news internal template will be removed in a future release. Please remove calls to this template. See https://github.com/gohugoio/hugo/issues/9172 for additional information.
WARN 2022/06/09 19:43:26 .Path when the page is backed by a file is deprecated and will be removed in a future release. We plan to use Path for a canonical source path and you probably want to check the source is a file. To get the current behaviour, you can use a construct similar to the one below:

  {{ $path := "" }}
  {{ with .File }}
        {{ $path = .Path }}
  {{ else }}
        {{ $path = .Path }}
  {{ end }}


Re-run Hugo with the flag --panicOnWarning to get a better error message.
```

In addition, in order to make future upgrades to the theme more manageable, we'd like to adopt [Hugo modules](https://gohugo.io/hugo-modules/) rather than the current approach of git submodules. Docsy does have [instructions](https://www.docsy.dev/docs/updating/) for both, and they have been followed in testing, but there are issues after at least the git submodule update approach with which we need help. For example, the center class isn't resolved.

<img width="1215" alt="image" src="https://user-images.githubusercontent.com/29008123/172963700-344d1881-841c-42b6-b82f-8c2c8e7c9558.png">

In general, we need a bit of hand-holding to help get caught up-to-date with this theme, resolve the issues doing so brings, and putting ourselves in a better position for future management of the site.

**Comment by chalin** [comment]
I took a cursory look. The good news is that your project is using Hugo 0.82.0, which isn't too ancient, https://github.com/kyverno/website/blob/287e2809f6e07fc03d24dbd6867450335e5ad1c3/netlify.toml#L8

Docsy hasn't been updated since the fall of 2020, which is quite old. Also, your project has Docsy overrides (e.g., layouts): these often make the update process considerably more burdensome.

Docsy is dropping the recursive Git submodules this quarter. I'd suggest that you keep using Docsy via a Git submodule for now -- at least until the project has updated both Hugo and Docsy.
