### ISSUE TITLE
render enhancements

### ISSUE THREAD

**Issue by JimBugwadia** [kyverno/website#59]
From: https://github.com/kyverno/policies/pull/7#issuecomment-752960677

Might be good to make this process more "go newbie" friendly such as:
Add step to chmod +x the render binary after go build process.
May need to change the output of the build process to be something other than render if executed in the root of the website dir since render already exists as a directory.
Link to instructions on how to install go(?)
When I run render on the current state of the policies repo, it's generating title and linkTitle with dashes and not with spaces (as the MD files currently have). weight is also different. Haven't checked the code.

**Comment by chipzoller** [comment]
May need a diffing ability to support policy YAML removals. Rendering is one way currently (YAML source => MD files), and when an MD is rendered, the source policy file is removed, the resulting MD has to be manually deleted.

**Comment by chipzoller** [comment]
We could really use some fixes here including solving of the double slash and ability to render into a relative directory with ability to overwrite existing files. Currently the render program is a multi-step process when trying to refresh all the rendered policies.

**Comment by JimBugwadia** [comment]
Chip, can you please provide more details on each requirement? These do not seem difficult to do, but want to make sure I understand the asks correctly.

**Comment by chipzoller** [comment]
Yes, certainly.

1. When calling `render`, somewhere in the Go it produces double slashes within the Markdown files. While this does not cause any noticeable problems, it isn't correct. For example, this is what is rendered under the Policy Definition header which provides the link back to the corresponding policy YAML file in kyverno/policies: `<a href="https://github.com/kyverno/policies/raw/main//best-practices/disallow_cri_sock_mount/disallow_cri_sock_mount.yaml" target="-blank">/best-practices/disallow_cri_sock_mount/disallow_cri_sock_mount.yaml</a>
`. You can observe the double slash between `main` and `best-practices` in the `a href` tag.
2. When cloning kyverno/website locally, which means it will be cloned with the Markdown files for all the policies, and then running `render`, all the policies will be rendered to the working directory for `render` which is the `/render` directory. The `render` binary does not accept a location for these files in relation to the working directory, for example `../content/en/policies` (which is where they all end up).
3. Further to number two above, the `render` program should be able to, if an optional flag is passed, overwrite files in the destination directory if present. The result of numbers two and three would be only a single-step process to render new policies whereas, presently, it's more than that as they need to be rendered, the destination directory cleared (optional), then moved, then committed.
4. When there's a failure encountered by `render` in the output, it can be tricky to spot because you have to scroll back through all the output (which gets lengthier the more policies we add) and ensure there were no errors thrown. Sometimes this has resulted in Markdown files being absent when such an error is encountered. It'd be very nice if `render` could collect any errors encountered and show them as the final output on a run (and exiting with a `1` for automation purposes) so it's clear what steps need to be taken.

Hopefully this all makes sense.

**Comment by chipzoller** [comment]
Include https://github.com/kyverno/website/issues/547

**Comment by chipzoller** [comment]
Double slashes still appear in output.

**Comment by JimBugwadia** [comment]
Please create an issue with the full command details.
