### ISSUE TITLE
[Enhancement] Update community off-boarding guidelines

### ISSUE THREAD

**Issue by JimBugwadia** [kyverno/website#810]
### Description

The [off-boarding guidelines](https://kyverno.io/community/#off-boarding-guidance) require some enhancements:

1. Clarify the process to inform the member. Ideally this is a public process e.g. via a Git issue.
2. Clarify how we determine inactivity. [DevStats](https://kyverno.devstats.cncf.io/d/66/developer-activity-counts-by-companies?orgId=1&var-period_name=Last+quarter&var-metric=contributions&var-repogroup_name=All&var-country_name=All&from=1522810884223&to=1680577284223) is the recommended source. 
3. Differentiate between members that are capable (i.e. there are no performance or skills issues) but have become inactive vs. members that are found to be not capable of adequately performing their duties but are active. This distinction may require additional documentation if off-boarding is initiated due to lack of capabilities.

**Comment by MarcelMue** [comment]
I have a few comments here which may or may not be helpful:

Towards 1. - I think having a Github issue out in public is a good way to keep the process transparent. It might be a reasonable idea to talk to the person first on Slack before the Issue is created (might help to prevent public conflict?) - but not sure how that is done in other projects.

Towards 2. I think tracking via DevStats is a good idea, it gives at least a rough impression of activity. Another indicator could be the "attendee" list in public meetings (e.g. maintainer meeting). It gives some data points which are objective in terms of participation.
Slack stats will be more difficult, as they are only really available to Slack admins AFAIK.

I think the third point is by far the hardest to clarify. It would require an audit of the activity in some form which determines that the performance is an issue. Making the outcome and steps within the process public would not happen in (for example) and employment situation - so I am not sure how it should be handled in a public project such as Kyverno.
Have there been cases where other projects handled such a situation?
